# Generated by Django 5.2.16 on 2026-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable service name shown in templates and admin.",
                        max_length=150,
                        verbose_name="name",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Optional logo image displayed next to the service name.",
                        upload_to="ecosystem/logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Absolute URL of the external service.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("HEADER", "Header"),
                            ("FOOTER", "Footer"),
                            ("SIDEBAR", "Sidebar"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        help_text="Placement group used when filtering services in templates.",
                        max_length=20,
                        verbose_name="location",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower values appear first. Ties are broken by name.",
                        verbose_name="display order",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive services are hidden from template tags.",
                        verbose_name="active",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, links open in a new browser tab.",
                        verbose_name="open in new tab",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ("display_order", "name"),
                "indexes": [
                    models.Index(
                        fields=["active", "location", "display_order", "name"],
                        name="ecosystem_svc_active_loc_ord",
                    )
                ],
            },
        ),
    ]
