# Generated by Django 5.2.16 on 2026-07-25 09:16

from __future__ import annotations

from django.db import migrations, models
from django.utils.text import slugify


def populate_service_slugs(apps, schema_editor) -> None:
    """Backfill unique slugs for existing services before enforcing uniqueness."""
    Service = apps.get_model("ecosystem", "Service")
    used_slugs: set[str] = set()

    for service in Service.objects.all().order_by("pk"):
        base_slug = slugify(service.name) or f"service-{service.pk}"
        candidate = base_slug
        suffix = 2
        while candidate in used_slugs:
            candidate = f"{base_slug}-{suffix}"
            suffix += 1
        service.slug = candidate
        service.save(update_fields=["slug"])
        used_slugs.add(candidate)


def noop_reverse(apps, schema_editor) -> None:
    """No reverse data migration required for slug backfill."""


class Migration(migrations.Migration):

    dependencies = [
        ("ecosystem", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="service",
            new_name="ecosystem_svc_lookup_idx",
            old_name="ecosystem_svc_active_loc_ord",
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional longer description for future display contexts.",
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text=(
                    "Unique URL-safe identifier. Generated from the name when left empty."
                ),
                max_length=150,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_service_slugs, noop_reverse),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Unique URL-safe identifier. Generated from the name when left empty."
                ),
                max_length=150,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive services are hidden from template tags.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower values appear first. Ties are broken by name.",
                verbose_name="display order",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="location",
            field=models.CharField(
                help_text=(
                    'Free-form placement key used by the template tag '
                    '(for example "footer", "pricing_page", or "dashboard_left").'
                ),
                max_length=100,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional logo image displayed next to the service name.",
                upload_to="ecosystem/services/",
                verbose_name="logo",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["location"], name="ecosystem_svc_location_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["active"], name="ecosystem_svc_active_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["display_order"], name="ecosystem_svc_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="ecosystem_svc_slug_idx"),
        ),
    ]
