# Generated by Django 5.2.16 on 2026-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecosystem",
            "0002_rename_ecosystem_svc_active_loc_ord_ecosystem_svc_lookup_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="service",
            name="ecosystem_svc_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="ecosystem_svc_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="ecosystem_svc_slug_idx",
        ),
        migrations.AlterField(
            model_name="service",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Only active services are returned by template tags.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional notes for editors. Reserved for future display use.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Sort key within a location. Lower values come first.",
                verbose_name="display order",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="location",
            field=models.CharField(
                help_text='Placement key matched exactly by the template tag (examples: "footer", "pricing_page", "dashboard_left").',
                max_length=100,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional image stored under MEDIA_ROOT/ecosystem/services/.",
                upload_to="ecosystem/services/",
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                help_text="Label shown in the admin and in default templates.",
                max_length=150,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="open_in_new_tab",
            field=models.BooleanField(
                default=True,
                help_text='Adds target="_blank" and rel="noopener noreferrer" when enabled.',
                verbose_name="open in new tab",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable unique identifier. Leave blank to generate from the name; existing values are kept when the name changes.",
                max_length=150,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="url",
            field=models.URLField(
                help_text="Absolute http(s) URL of the external service.",
                verbose_name="URL",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("location", ""), _negated=True),
                name="ecosystem_svc_location_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("slug", ""), _negated=True),
                name="ecosystem_svc_slug_not_empty",
            ),
        ),
    ]
