# Generated by Django 5.2.16 on 2026-08-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecosystem", "0005_alter_service_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="key",
            field=models.CharField(
                help_text='Stable template-tag identifier (for example "footer" or "pricing_page"). Must match the ecosystem template tag argument exactly. Changing an existing key breaks those template usages. Surrounding whitespace is trimmed automatically.',
                max_length=100,
                unique=True,
                verbose_name="key",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this service everywhere without deleting it.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional notes for your team. Not shown on the site by default.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="location",
            field=models.ForeignKey(
                help_text="Placement this service belongs to. The placement key must match the argument used in the ecosystem template tag.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="ecosystem.location",
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional image shown next to the service name (stored under MEDIA_ROOT/ecosystem/services/).",
                upload_to="ecosystem/services/",
                verbose_name="logo",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                help_text='Short label visitors and editors will recognize (for example "Academy" or "Shop").',
                max_length=150,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="open_in_new_tab",
            field=models.BooleanField(
                default=True,
                help_text="When checked, the link opens in a new browser tab.",
                verbose_name="open in new tab",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="position",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order within the location. Managed automatically — use the location workspace to reorder. Lower values appear first.",
                verbose_name="position",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Internal unique ID. Leave blank to generate from the name; existing values are kept when the name changes.",
                max_length=150,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="url",
            field=models.URLField(
                help_text="Full web address, including https:// (for example https://academy.example.com).",
                verbose_name="URL",
            ),
        ),
    ]
